/**
 * Generates a PromptFoo redteam YAML config from scan parameters.
 * Uses the native `redteam` section so `promptfoo redteam run` works correctly.
 */

export interface ScanParams {
  targetUrl: string
  targetType: 'http' | 'openai' | 'anthropic' | 'custom'
  purpose?: string
  systemPrompt?: string
  plugins: string[]
  strategies: (string | { id: string; config: Record<string, unknown> })[]
  numTests: number
  responseParser?: string
}

export function buildRedteamConfig(params: ScanParams): string {
  const {
    targetUrl,
    targetType,
    purpose,
    systemPrompt,
    plugins,
    strategies,
    numTests,
    responseParser,
  } = params

  const target = buildTarget(targetUrl, targetType, responseParser)

  const pluginYaml = plugins.map(p => `    - id: '${p}'`).join('\n')

  let strategyYaml: string
  if (!strategies || strategies.length === 0) {
    strategyYaml = '  strategies: []'
  } else {
    const items = strategies.map(s => {
      if (typeof s === 'string') return `    - id: '${s}'`
      return [
        `    - id: '${s.id}'`,
        `      config:`,
        ...formatNestedConfig(s.config, 8),
      ].join('\n')
    }).join('\n')
    strategyYaml = `  strategies:\n${items}`
  }

  let yaml = `# Auto-generated by PandaExploit AI Security
description: "Red Team Scan for ${escapeYaml(targetUrl)}"

targets:
${target}

redteam:
  numTests: ${numTests}
`

  if (purpose) {
    yaml += `  purpose: "${escapeYaml(purpose)}"\n`
  }

  yaml += `  plugins:\n${pluginYaml}\n`
  yaml += `${strategyYaml}\n`

  if (systemPrompt) {
    yaml += `\nprompts:\n  - "${escapeYaml(systemPrompt)}\\n\\n{{prompt}}"\n`
  }

  return yaml
}

function buildTarget(url: string, type: string, responseParser?: string): string {
  const isDefaultOpenAI = !url || url === 'https://api.openai.com/v1/chat/completions'
  const isDefaultAnthropic = !url || url === 'https://api.anthropic.com/v1/messages'

  switch (type) {
    case 'openai': {
      const model = 'openai:chat:gpt-4o'
      if (isDefaultOpenAI) {
        return `  - id: '${model}'`
      }
      return [
        `  - id: '${model}'`,
        `    config:`,
        `      apiBaseUrl: "${url}"`,
      ].join('\n')
    }

    case 'anthropic': {
      const model = 'anthropic:messages:claude-3-sonnet-20240229'
      if (isDefaultAnthropic) {
        return `  - id: '${model}'`
      }
      return [
        `  - id: '${model}'`,
        `    config:`,
        `      apiBaseUrl: "${url}"`,
      ].join('\n')
    }

    case 'http':
    default:
      return [
        `  - id: 'http'`,
        `    config:`,
        `      url: "${url}"`,
        `      method: POST`,
        `      headers:`,
        `        Content-Type: application/json`,
        `      body:`,
        `        prompt: "{{prompt}}"`,
        `      responseParser: "${responseParser || 'json.response'}"`,
      ].join('\n')
  }
}

function formatNestedConfig(config: Record<string, unknown>, indent: number): string[] {
  const pad = ' '.repeat(indent)
  const lines: string[] = []
  for (const [key, value] of Object.entries(config)) {
    if (Array.isArray(value)) {
      lines.push(`${pad}${key}:`)
      for (const item of value) {
        lines.push(`${pad}  - ${typeof item === 'string' ? item : JSON.stringify(item)}`)
      }
    } else if (typeof value === 'object' && value !== null) {
      lines.push(`${pad}${key}:`)
      lines.push(...formatNestedConfig(value as Record<string, unknown>, indent + 2))
    } else {
      lines.push(`${pad}${key}: ${JSON.stringify(value)}`)
    }
  }
  return lines
}

function escapeYaml(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n')
}
